/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint32_t *RCC_CR = (uint32_t*) 0x40021000;
uint32_t *RCC_CFGR = (uint32_t*) 0x40021004;
uint32_t *RCC_AHBENR = (uint32_t*) 0x40021014;

uint32_t *GPIOC_MODER = (uint32_t*) 0x48000800;
uint32_t *GPIOC_OTYPER = (uint32_t*) 0x48000804;
uint32_t *GPIOC_ODR = (uint32_t*) 0x48000814;

int main(void)
{
	*RCC_CFGR = (1U << 31U)|(7U << 24U)|(4U << 18U)|(2U << 15U)|(2U << 0U);
	*RCC_CR = (1U << 24U);
	*RCC_AHBENR = (1U << 19U);

	*GPIOC_MODER = (1U << 26U);
	*GPIOC_OTYPER = (1U << 13U);

	*GPIOC_ODR = (0U << 13U);
	*GPIOC_ODR = (1U << 13U);
	/* Loop forever */
	for(;;);
}
