/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdbool.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay_ms(int time);
void loop();
void pwm();
void blink();
//void EXTI0_1_IRQHandler();

uint32_t *RCC_CR = (uint32_t*) 0x40021000;
uint32_t *RCC_CFGR = (uint32_t*) 0x40021004;
uint32_t *RCC_CIR = (uint32_t*) 0x40021008;
uint32_t *RCC_APB2RSTR = (uint32_t*) 0x4002100C;
uint32_t *RCC_APB1RSTR = (uint32_t*) 0x40021010;
uint32_t *RCC_AHBENR = (uint32_t*) 0x40021014;
uint32_t *RCC_APB2ENR = (uint32_t*) 0x40021018;
uint32_t *RCC_APB1ENR = (uint32_t*) 0x4002101C;
uint32_t *RCC_BDCR = (uint32_t*) 0x40021020;
uint32_t *RCC_CSR = (uint32_t*) 0x40021024;
uint32_t *RCC_AHBRSTR = (uint32_t*) 0x40021028;
uint32_t *RCC_CFGR2 = (uint32_t*) 0x4002102C;
uint32_t *RCC_CFGR3 = (uint32_t*) 0x40021030;
uint32_t *RCC_CR2 = (uint32_t*) 0x40021034;

uint32_t *GPIOB_MODER = (uint32_t*) 0x48000400;
uint32_t *GPIOB_OTYPER = (uint32_t*) 0x48000004;
uint32_t *GPIOB_OSPEEDR = (uint32_t*) 0x48000408;
uint32_t *GPIOB_PUPDR = (uint32_t*) 0x4800040C;
uint32_t *GPIOB_IDR = (uint32_t*) 0x48000410;
uint32_t *GPIOB_ODR = (uint32_t*) 0x48000414;
uint32_t *GPIOB_BSRR = (uint32_t*) 0x48000418;
uint32_t *GPIOB_LCKR = (uint32_t*) 0x4800041C;
uint32_t *GPIOB_AFRL = (uint32_t*) 0x48000420;
uint32_t *GPIOB_AFRH = (uint32_t*) 0x48000424;
uint32_t *GPIOB_BRR = (uint32_t*) 0x48000428;

uint32_t *GPIOC_MODER = (uint32_t*) 0x48000800;
uint32_t *GPIOC_OTYPER = (uint32_t*) 0x48000804;
uint32_t *GPIOC_OSPEEDR = (uint32_t*) 0x48000808;
uint32_t *GPIOC_PUPDR = (uint32_t*) 0x4800080C;
uint32_t *GPIOC_IDR = (uint32_t*) 0x48000810;
uint32_t *GPIOC_ODR = (uint32_t*) 0x48000814;
uint32_t *GPIOC_BSRR = (uint32_t*) 0x48000818;
uint32_t *GPIOC_LCKR = (uint32_t*) 0x4800081C;
uint32_t *GPIOC_AFRL = (uint32_t*) 0x48000820;
uint32_t *GPIOC_AFRH = (uint32_t*) 0x48000824;
uint32_t *GPIOC_BRR = (uint32_t*) 0x48000828;

uint32_t *TIM3_CR1 = (uint32_t*) 0x40000400;
uint32_t *TIM3_CR2 = (uint32_t*) 0x40000404;
uint32_t *TIM3_SMCR = (uint32_t*) 0x40000408;
uint32_t *TIM3_DIER = (uint32_t*) 0x4000040C;
uint32_t *TIM3_SR = (uint32_t*) 0x40000410;
uint32_t *TIM3_EGR = (uint32_t*) 0x40000414;
uint32_t *TIM3_CCMR1 = (uint32_t*) 0x40000418;
uint32_t *TIM3_CCMR2 = (uint32_t*) 0x4000041C;
uint32_t *TIM3_CCER = (uint32_t*) 0x40000420;
uint32_t *TIM3_CNT = (uint32_t*) 0x40000424;
uint32_t *TIM3_PSC = (uint32_t*) 0x40000428;
uint32_t *TIM3_ARR = (uint32_t*) 0x4000042C;
uint32_t *TIM3_CCR1 = (uint32_t*) 0x40000434;
uint32_t *TIM3_CCR2 = (uint32_t*) 0x40000438;
uint32_t *TIM3_CCR3 = (uint32_t*) 0x4000043C;
uint32_t *TIM3_CCR4 = (uint32_t*) 0x40000440;
uint32_t *TIM3_DCR = (uint32_t*) 0x40000448;
uint32_t *TIM3_DMAR = (uint32_t*) 0x4000044C;

uint32_t *SYSCFG_CFGR1 = (uint32_t*) 0x40010000;
uint32_t *SYSCFG_EXTICR1 = (uint32_t*) 0x40010008;


uint32_t *NVIC_ISER = (uint32_t*) 0xE000E100;
uint32_t *NVIC_ICER = (uint32_t*) 0XE000E180;
uint32_t *NVIC_ISPR = (uint32_t*) 0XE000E200;
uint32_t *NVIC_ICPR = (uint32_t*) 0XE000E280;
uint32_t *NVIC_IPR0 = (uint32_t*) 0xE000E400;

uint32_t *EXTI_IMR = (uint32_t*) 0x40010400;
uint32_t *EXTI_EMR = (uint32_t*) 0x40010404;
uint32_t *EXTI_RTSR = (uint32_t*) 0x40010408;
uint32_t *EXTI_FTSR = (uint32_t*) 0x4001040C;
uint32_t *EXTI_SWIER = (uint32_t*) 0x40010410;
uint32_t *EXTI_PR = (uint32_t*) 0x40010414;
uint32_t *EXTI0_1 = (uint32_t*) 0x00000054;

int i = 4800;
bool led = 1;

int main(void)
{
	*RCC_CR = (1U << 16U);
	while(!(*RCC_CR & (1U << 17U)));

	*RCC_APB1ENR = (1U << 28U)|(1U << 1U);
	*RCC_APB2ENR = (1U);

//	*RCC_CFGR = (1U << 31U)|(7U << 24U)|(4U << 18U)|(2U << 15U)|(2U << 0U);
	*RCC_CFGR = (1U << 31U)|(4U << 18U)|(2U << 15U)|(2U << 0U);
//	*RCC_AHBENR = (1U << 22U)|(1U << 19U);

//	*RCC_APB2ENR =

	*RCC_AHBENR = (1U << 19U)|(1U << 18U)|(1U << 17U);
	*RCC_CR |= (1U << 24U);
	while(!(*RCC_CR & (1U << 25)));

	*GPIOC_MODER = (1U << 26U);
	*GPIOC_OSPEEDR = (3U << 26U);
	*GPIOC_OTYPER = (1U << 13U);

	*GPIOB_MODER |= (2U << 10U)|(2U << 8U)|(1U << 6U)|(2U << 2U)|(2U);
	*GPIOB_OSPEEDR |= (2U << 10U)|(2U << 8U)|(1U << 6U)|(2U << 2U)|(2U);
//	*GPIOA_OTYPER = (1U << 14U)|(1U << 12U);
	*GPIOB_AFRL |= (1U << 20U)|(1U << 16U)|(1U << 4U)|(1U);

	*TIM3_CR1 = (1U << 7U);
	*TIM3_ARR = (4800U);
	*TIM3_PSC = (100U);
	*TIM3_CCR1 = (0U);
	*TIM3_CCR2 = (0U);
	*TIM3_CCR3 = (0U);
	*TIM3_CCR4 = (0U);
	*TIM3_CCMR1 = (6U << 12U)|(6U << 4U);
	*TIM3_CCMR2 = (6U << 12U)|(6U << 4U);
	*TIM3_CCER = (1U << 12U)|(1U << 8U)|(1U << 4U)|(1U);
	*TIM3_CR1 |= (1U);

	*SYSCFG_EXTICR1 = (0U);

	*EXTI_IMR |= (1U);
	*EXTI_FTSR |= (1U);

	*NVIC_IPR0 |= (0U);
	*NVIC_ISER |= (1U);

//	*EXTI_EMR = (1U << 4U);
//	*EXTI_SWIER = (1U << 4U);
	/* Loop forever */
	for(;;)
	{
		loop();
	}
}

void loop()
{
//	pwm();
	if(led)
	{
		*TIM3_CCR3 = (4800*0.833); // Red
		*TIM3_CCR1 = (4800*0.327); // Green
		*TIM3_CCR4 = (4800); //Blue
	}
	else
	{
		*TIM3_CCR3 = (0); // Red
		*TIM3_CCR1 = (0); // Green
		*TIM3_CCR4 = (4800*1); //Blue
	}
}

void EXTI0_1_IRQHandler()
{
	while(1);
	*EXTI_PR = (1U);
	led = !led;
}

void pwm()
{
	for(int i = 0; i < (4800*0.733); i++) // Red LED
	{
		*TIM3_CCR3 = (i);
		delay_ms(1000);
	}
	for(int i = 0; i < (4800*0.327); i++) // Green LED
	{
		*TIM3_CCR1 = (i);
		delay_ms(1000);
	}
	for(int i = 0; i < (4800*1); i++) //Blue LED
	{
		*TIM3_CCR4 = (i); //B
		delay_ms(1000);
	}
	for(int i = (4800*0.733); i > 0; i--) // Red LED
	{
		*TIM3_CCR3 = (i);
		delay_ms(1000);
	}
	for(int i = (4800*0.827); i > 0; i--) // Green LED
	{
		*TIM3_CCR1 = (i);
		delay_ms(1000);
	}
	for(int i = (4800*1); i > 0; i--) // Blue LED
	{
		*TIM3_CCR4 = (i);
		delay_ms(1000);
	}
}

void blink()
{
//	*GPIOC_BSRR = (1U << 13U);
//	*GPIOC_BSRR = (1U << 29U);
	*GPIOC_ODR = (0U << 13U);
	*GPIOB_ODR = (0U << 3U);
	delay_ms(100000);
	*GPIOC_ODR = (1U << 13U);
	*GPIOB_ODR = (1U << 3U);
	delay_ms(100000);
}

// Not exactly in ms
void delay_ms(int time)
{
	int i = 0;
	while(i < (2 * time))
	{
		i++;
	}
}
